# Generated by Django 3.2.7 on 2022-03-12 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('content', models.TextField(max_length=1050)),
                ('topic', models.TextField(max_length=1050)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
